### PR TITLE
Create Invoke-IcingaCheckNLA.psm1

### PR DESCRIPTION
**Pull request by DoktorAerzt**
I created a script to check if a nic have a specific firewall profile.
In other words. Of the network location awareness is working correctly.

I hope the script will fulfill your guidelines.

### CODE REVIEW

**Comment by LordHepipud** [comment]
Thank you for your contribution. I will have a look on it on Monday and get back to you afterwards. Looks very promising for far - thanks a lot :-)

**Comment by LordHepipud** [comment]
I have tested the plugin today and it seems to work fine. Do we hoever require performance data for the checks?
The current performance data output is not required in my oppinion and could be removed.

What do you think?

**Comment by DoktorAerzt** [comment]
I think that it´s not important but i used Invoke-IcingaCheckFirewall.psm1 as template. And that's why i added the performance data because i think it should be for bove plugins the same. Because they are similar.

**Comment by LordHepipud** [comment]
Ah, I see. Yes, that output is as well not useful in my oppinion.
I will fix this.

**Comment by LordHepipud** [comment]
I made some slight adjustment to the plugin. What do you think?

**Comment by DoktorAerzt** [comment]
Looks great. Thank you.

**Comment by LordHepipud** [comment]
Great job with the Plugin - thank you for your contribution!

**Pull request merged**
