### PR TITLE
added param to ignore certain task-exit-codes for Invoke-IcingaCheckScheduledTask

### LINKED ISSUE #282: Invoke-IcingaCheckScheduledTask ignore certain return codes
I started monitoring different Windows-Tasks with the Invoke-IcingaCheckScheduledTask commandlet.

One of these tasks is running pretty long (about 45 Minutes). While this task is running the check-command returns a non 0 return code 41301 (task is running). If I do not ignore the return codes it will show up as critical, which is not specifically the "correct" result in this case. So I have to ignore the return codes for now.

I see two possible ways around this problem. One would be to ignore this specific exit code if the state "Running" is allowed. The other one is to add another configuration-parameter to give a list of return codes that should specifically be ignored, e.g. 41301 for task is running or  41306 for task has been terminated by the user. Maybe even implement both solutions?

Opinions on this?

### PR DESCRIPTION
**Pull request by Paul-Weisser**
Fixes #282

### CODE REVIEW

**Comment by Paul-Weisser** [comment]
@cla-bot check

**Comment by Paul-Weisser** [comment]
@cla-bot check

**Comment by bobapple** [comment]
@cla-bot check

**Comment by LordHepipud** [comment]
Thanks!

**Pull request merged**
