### PR TITLE
Create Invoke-IcingaCheckProcessRunning.psm1

### PR DESCRIPTION
**Pull request by DoktorAerzt**
I wasn´t sure to create one or 2 pr for the plugins. 

This plugin checks if a process is running or not and will return OK or CRITICAL

### CODE REVIEW

**Comment by LordHepipud** [comment]
Thank you for your contribution ! Was there a specific reason on why you are not using the `Invoke-IcingaCheckProcessCount` plugin?

As far as I understand both are doing the same thing - or am I mistaken here?

**Comment by DoktorAerzt** [comment]
The point is, if i unterstand ```Invoke-IcingaCheckProcessCount``` correct, you only can check how many processes are running and get a warning or critical when to many are running. 

```Invoke-IcingaCheckProcessRunning``` checks if a process is running and you get an critical if it is not running. 

I think one solution whould be to negate ```Invoke-IcingaCheckProcessCount```

**Comment by LordHepipud** [comment]
You could already do that, because the Process Check Plugin is following the Icinga / Nagios Development Guides for Thresholds. To check if a process is running, the command would look like this

```powershell
Invoke-IcingaCheckProcessCount -Process Firefox-Critical '1:'
```

Output

```powershell
[CRITICAL] Check package "Process Check" - [CRITICAL] Process Count "Firefox"
\_ [CRITICAL] Process Count "Firefox": Value "0" is lower than threshold "1"
| 'process_count_msedge2'=0;;1:
```

Does this help you and matches your requirements?

**Comment by DoktorAerzt** [comment]
Perfect that was exactly what i want. 
I close this pr.

**Comment by LordHepipud** [comment]
Allright - Thank you. I will extend the documentation on that a little more, to ensure everyone will be aware of this :)

**Pull request closed without merging**
