### PR TITLE
Added exclusion possibility for certificates

### PR DESCRIPTION
**Pull request by chaozmc**
Added an Array (ExcPatterns) which can include strings to loop through and check for each certificate if the searched string is included in subject, issuer or SAN field.

### CODE REVIEW

**Comment by chaozmc** [comment]
Sorry I didn't realize that a new commit would also be included in the same pull-request. I'm unexperienced with the PullRequest feature. I thought i can open another one for the next commit(s).

However, I found problem with certificates which have an empty subject. In that case it's useful to return the property DnsNameList, which contains the value of the SAN field but without the DNS= prefix. If there are more than one DNS= entry the property contains all of them seperated by NewLine, therefore the second commit was necessary to change the return value to the first element.

**Comment by LordHepipud** [comment]
Hello, don't worry - it's fine.
I will test the PR and check if there is an issue.

Just one addition from my side: Would it be possible to rename the function `Test-IfExcluded` to something like `Test-IcingaCertificateExcludePattern`? This will ensure we understand the handling better. In addition it would be great if you could create a new `.psm1` file for this function inside the certificate provider folder and add a documentation for both, the new argument as well as the function itself.

By doing so everyone will know how to use it and how a exclude pattern shall look like.

If everything is done you can also squash all commits to one single commit for this feature.

Thank you in advance and thanks for the contribution!

**Comment by LordHepipud** [comment]
Thank you again for the PR and sorry for the long delay. I did some small adjustments on inednting and removed trailing white spaces.
Could you please have a look if everything is fine? If so, it would be great if you would squash everything to one commit (it will then also remove my name on the commits :D )

Afterwards I can merge it.

Thank you again !

**Comment by chaozmc** [comment]
Hi! 

Don't worry I was very busy too. Everything looks fine so far for me. I just found a typo in the description of the ExcludePattern parameter description.
 
Unfortunately i don't know how i could do that "squash everything to one commit" :( is this some function on the website or has it done via git cli / GitHub Desktop? I'd be fine too if your name is listed beside the commits - it doesn't really matter to me.

**Comment by LordHepipud** [comment]
Thanks!

**Pull request merged**
